### ISSUE TITLE
TypeError: Console expects a writable stream instance

### ISSUE THREAD

**Issue by doomcha** [indiesoftby/defold-playable-ads#13]
First of all, thank you very much for such amazing tool! 

I have a little problem when calling `gulp` in the playable_ad folder. 

`TypeError: Console expects a writable stream instance
    at new Console (console.js:35:11)
    at Object.<anonymous> (c:\Projects\html5games\playable_ad\node_modules\gulp-download-stream\node_modules\fancy-log\index.js:7:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Projects\html5games\playable_ad\node_modules\gulp-download-stream\index.js:9:11)`
    
My Node JS Version: 20.10.0 (includes npm 10.2.3)

I use the temp fix for that:
Openning playable_ad\node_modules\gulp-download-stream\node_modules\fancy-log\index.js at 7:15
And replacing 
`var console = new Console({
  stdout: process.stdout,
  stderr: process.stderr,
  colorMode: false,
});`
to 
`var console = new Console(process.stdout,process.stderr);`

But the problem is every time I clean node_modules I have to fix that again (obviously). It would be nice to have some permanent fix for that, if possible. Hope for your help! Thanks!

**Comment by aglitchman** [comment]
I'll look it up for sure! 

But I'm not able to reproduce the problem yet. Internet search suggests that this problem is inherent in an older version of NodeJS. Strange.

**Comment by doomcha** [comment]
Thanks!
Yep, that's strange indeed...  what version of NodeJS do you use?

**Comment by aglitchman** [comment]
> Thanks! Yep, that's strange indeed... what version of NodeJS do you use?

You have this error as if you have nodejs version 8 or 10, when it didn't support the new arguments in `new Console()` yet. Very strange.

I installed v20.10.0 for the tests.

```
[11:10:17] * playable_ad_example_archive.js size 948873 B (949 kB)
[11:10:17] * dmloader.js zstd + base64 encoded size 5617 B (5.62 kB)
[11:10:17] * playable_ad_example.html resulting size 987849 B (988 kB)
[11:10:17] Finished 'bundlePlayableAds' after 649 ms
[11:10:17] Finished 'default' after 7.49 s

C:\Users\Artsiom\Documents\Defold\ext_playable_ads\playable_ad>node -v
v20.10.0

C:\Users\Artsiom\Documents\Defold\ext_playable_ads\playable_ad>
```

**Comment by doomcha** [comment]
Hehe, me stupid damsel X)

```
c:\Projects\html5games\playable_ad>node -v

v8.12.0
```


Probably I have 2 versions installed on my PC and launching it with the old one. So, it seems like updating node js will fix the issue. Thanks a lot for your help and sorry for bothering you!
